# HTTP Server
server:
  port: ${ADMIN_SERVER_PORT:9999}   # HTTP port
  
# Discovery Server Access
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
     # defaultZone: ${EUREKA_ENDPOINT}
  instance:
     preferIpAddress: true
   
#Security
spring:
  security:
    user:
      name: admin
      password: admin