# HTTP Server
server:
  port: ${PORT:3333}   # HTTP port

# Discovery Server Access
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

spring:
  boot:
    admin:
      client:
        url: http://localhost:9999
        username: admin
        password: admin
      
logging:
  file: logs/${spring.application.name}.log
  level:
    com.netflix.discovery: 'OFF'
    org.springframework.cloud: 'INFO'
    org.springframework.web: 'INFO'
    com.microservicio: 'DEBUG'
