server:  
  port: ${PORT:2222}

eureka:  
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
      
logging:
  file: logs/${spring.application.name}.log
  level:
    com.netflix.discovery: 'OFF'
    org.springframework.cloud: 'INFO'
    org.springframework.web: 'INFO'
    com.microservicio: 'DEBUG'
    
microservicio:
  contact:
    name: microservicio
    findAllUrl: http://localhost:3333/contact/findall/
    saveUrl: http://localhost:3333/contact/save/
    deleteUrl: http://localhost:3333/contact/delete/

spring:
   rabbitmq:
     host: localhost
     port: 15672
     username: guest
     password: guest    
    # findAllUrl: http://${microservicio}/contact/findall/
    
